let cfg, token;
const $ = (selector) => document.querySelector(selector);
const tables = ['social_links', 'services', 'gallery_items', 'appointment_slots', 'reservations'];
const state = Object.fromEntries(tables.map((table) => [table, []]));
const mediaTypes = new Set(['image/jpeg', 'image/png', 'image/webp', 'video/mp4', 'video/webm', 'video/quicktime']);
const isVideo = (url = '') => /\.(mp4|webm|mov)(\?.*)?$/i.test(url);
document.head.insertAdjacentHTML('beforeend', '<style>.item-head{min-width:0}.media-row{min-width:0;flex:1}.media-row>div{min-width:0}.item-actions{flex:0 0 auto}.item small,.item p{overflow-wrap:anywhere}@media(max-width:760px){.media-row{width:100%}}</style>');

function message(text, ok = false) { const el = $('#dashboard-message'); el.textContent = text; el.className = `message${ok ? ' ok' : ''}`; }
function escape(value = '') { const box = document.createElement('div'); box.textContent = String(value); return box.innerHTML; }
function setBusy(form, busy) { form.querySelectorAll('button').forEach((button) => { button.disabled = busy; }); }
async function api(path, options = {}) { const response = await fetch(path, { cache: 'no-store', ...options, headers: { Authorization: `Bearer ${token}`, 'Content-Type': 'application/json', ...options.headers } }); const body = response.status === 204 ? null : await response.json(); if (!response.ok) throw new Error(body?.error || 'The request could not be completed.'); return body; }
function bool(value) { return value === 'true'; }
function numeric(value) { return value === '' ? 100 : Number(value); }
function formatNaira(value = '') { const amount = Number(String(value).replace(/[^0-9.]/g, '')); return Number.isFinite(amount) && amount > 0 ? `₦${amount.toLocaleString('en-NG')}` : value; }
function displayName(table, row) { if (table === 'appointment_slots') return new Date(row.starts_at).toLocaleString('en-NG', { dateStyle: 'medium', timeStyle: 'short' }); if (table === 'reservations') return row.client_name; return row.title || row.platform; }
function detail(table, row) { if (table === 'appointment_slots') return row.is_available ? 'Available for booking' : 'Unavailable'; if (table === 'reservations') return `${row.phone} · ${row.status || 'pending'}`; return row.description || row.url || row.price || row.label || ''; }
function control(name, value = '', type = 'text', required = false) { return `<label>${name.replaceAll('_', ' ')}<input name="${name}" type="${type}" value="${escape(value)}" ${required ? 'required' : ''}></label>`; }
function select(name, value, trueLabel = 'Published', falseLabel = 'Draft') { return `<label>${name.replaceAll('_', ' ')}<select name="${name}"><option value="true" ${value ? 'selected' : ''}>${trueLabel}</option><option value="false" ${!value ? 'selected' : ''}>${falseLabel}</option></select></label>`; }
function editor(table, row) {
  if (table === 'services') return `${control('title', row.title, 'text', true)}${control('price', row.price, 'text', true)}<label>Description<textarea name="description" required>${escape(row.description)}</textarea></label>${control('sort_order', row.sort_order, 'number')}${select('is_published', row.is_published)}`;
  if (table === 'gallery_items') return `${control('title', row.title, 'text', true)}<label>Description<textarea name="description">${escape(row.description)}</textarea></label><label>Upload replacement photo or video<input name="media" type="file" accept="image/jpeg,image/png,image/webp,video/mp4,video/webm,video/quicktime"></label>${control('image_url', row.image_url, 'url')}${control('alt_text', row.alt_text, 'text', true)}${control('sort_order', row.sort_order, 'number')}${select('is_published', row.is_published)}`;
  if (table === 'social_links') return `${control('platform', row.platform, 'text', true)}${control('label', row.label)}${control('url', row.url, 'url', true)}${control('sort_order', row.sort_order, 'number')}${select('is_published', row.is_published)}`;
  if (table === 'appointment_slots') return `${control('starts_at', new Date(row.starts_at).toISOString().slice(0, 16), 'datetime-local', true)}${select('is_available', row.is_available, 'Available', 'Unavailable')}`;
  return `<label>Status<select name="status"><option value="pending" ${row.status === 'pending' ? 'selected' : ''}>Pending</option><option value="confirmed" ${row.status === 'confirmed' ? 'selected' : ''}>Confirmed</option><option value="completed" ${row.status === 'completed' ? 'selected' : ''}>Completed</option><option value="cancelled" ${row.status === 'cancelled' ? 'selected' : ''}>Cancelled</option></select></label>`;
}
function preview(row) { if (!row.image_url) return ''; const url = escape(row.image_url); return isVideo(row.image_url) ? `<video class="media-preview" muted preload="metadata" src="${url}"></video>` : `<img class="media-preview" src="${url}" alt="">`; }
function render(table) {
  const list = document.querySelector(`[data-list="${table}"]`); const records = state[table];
  list.innerHTML = records.length ? records.map((row) => `<article class="item"><div class="item-head">${table === 'gallery_items' ? `<div class="media-row">${preview(row)}<div>` : '<div>'}<h3>${escape(displayName(table, row))}</h3><p>${escape(detail(table, row))}</p><small>${table === 'gallery_items' ? 'Media saved' : table === 'reservations' ? `Received ${new Date(row.created_at).toLocaleString('en-NG')}` : row.is_published === false ? 'Draft' : ''}</small></div>${table === 'gallery_items' ? '</div>' : ''}<div class="item-actions"><button class="muted" data-edit="${table}" data-id="${row.id}">Edit</button><button class="muted danger" data-delete="${table}" data-id="${row.id}">Delete</button></div></div><form class="edit-form hidden" data-edit-form="${table}" data-id="${row.id}">${editor(table, row)}<div class="item-actions"><button>Save changes</button><button type="button" class="muted" data-cancel>Cancel</button></div></form></article>`).join('') : '<p class="empty">Nothing has been added here yet.</p>';
}
async function refresh(table) { state[table] = await api(`/api/admin/${table}`); render(table); }
async function upload(file) {
  if (!file?.size) return ''; if (!mediaTypes.has(file.type)) throw new Error('Choose a JPG, PNG, WEBP, MP4, WEBM or MOV file.'); if (file.size > 20 * 1024 * 1024) throw new Error('Media must be 20 MB or smaller.');
  const extension = file.name.split('.').pop().toLowerCase(); const path = `gallery/${crypto.randomUUID()}.${extension}`;
  const response = await fetch(`${cfg.supabaseUrl}/storage/v1/object/lash-media/${path}`, { method: 'POST', headers: { apikey: cfg.anonKey, Authorization: `Bearer ${token}`, 'Content-Type': file.type, 'x-upsert': 'false' }, body: file });
  if (!response.ok) throw new Error('Upload failed. Run supabase/full-cms-migration.sql in Supabase, then try again.');
  return `${cfg.supabaseUrl}/storage/v1/object/public/lash-media/${path}`;
}
function formValues(form) {
  const raw = new FormData(form); const values = Object.fromEntries([...raw].filter(([key, value]) => key !== 'media' && !(value instanceof File)));
  Object.entries(values).forEach(([key, value]) => { if (value === 'true' || value === 'false') values[key] = bool(value); if (key === 'sort_order') values[key] = numeric(value); if (['price'].includes(key)) values[key] = formatNaira(value); }); return values;
}
async function save(form, table, id) {
  const values = formValues(form); if (table === 'gallery_items') { const uploaded = await upload(new FormData(form).get('media')); if (uploaded) values.image_url = uploaded; if (!values.image_url) throw new Error('Choose media from this device or add a hosted image or video URL.'); }
  await api(`/api/admin/${table}${id ? `?id=${id}` : ''}`, { method: id ? 'PATCH' : 'POST', body: JSON.stringify(values) }); await refresh(table); message(id ? 'Changes saved. The live site now uses the updated content.' : 'Item saved. Published content is live now.', true);
}
async function boot() { const settings = await api('/api/admin/site_settings'); $('#settings-form').reservation_email.value = settings[0]?.reservation_email || ''; $('#settings-form').location.value = settings[0]?.location || 'Lagos, Nigeria'; await Promise.all(tables.map(refresh)); }
fetch('/api/config').then((response) => response.json()).then((data) => { cfg = data; if (!cfg.ready) $('#login-message').textContent = 'CMS is not connected yet. Add the environment values and restart the server.'; }).catch(() => { $('#login-message').textContent = 'Open this dashboard through the CMS server at http://localhost:3000/admin.'; });
$('#login-form').addEventListener('submit', async (event) => { event.preventDefault(); if (!cfg?.ready) return $('#login-message').textContent = 'Start the CMS server before signing in.'; setBusy(event.currentTarget, true); try { const credentials = formValues(event.currentTarget); const response = await fetch(`${cfg.supabaseUrl}/auth/v1/token?grant_type=password`, { method: 'POST', headers: { apikey: cfg.anonKey, 'Content-Type': 'application/json' }, body: JSON.stringify(credentials) }); const data = await response.json(); if (!response.ok) throw new Error(data.error_description || 'Unable to sign in.'); token = data.access_token; $('#login').classList.add('hidden'); $('#dashboard').classList.remove('hidden'); $('#sign-out').classList.remove('hidden'); await boot(); } catch (error) { $('#login-message').textContent = error.message; } finally { setBusy(event.currentTarget, false); } });
document.querySelectorAll('[data-create]').forEach((form) => form.addEventListener('submit', async (event) => { event.preventDefault(); setBusy(form, true); try { await save(form, form.dataset.create); form.reset(); } catch (error) { message(error.message); } finally { setBusy(form, false); } }));
document.addEventListener('blur', (event) => { if (event.target.matches('input[name="price"]')) event.target.value = formatNaira(event.target.value); }, true);
$('#settings-form').addEventListener('submit', async (event) => { event.preventDefault(); setBusy(event.currentTarget, true); try { await api('/api/admin/site_settings?id=1', { method: 'PATCH', body: JSON.stringify(formValues(event.currentTarget)) }); message('Reservation inbox saved successfully.', true); } catch (error) { message(error.message); } finally { setBusy(event.currentTarget, false); } });
document.addEventListener('click', async (event) => { const edit = event.target.closest('[data-edit]'); const remove = event.target.closest('[data-delete]'); const cancel = event.target.closest('[data-cancel]'); if (cancel) return cancel.closest('.edit-form').classList.add('hidden'); if (edit) return edit.closest('.item').querySelector('.edit-form').classList.remove('hidden'); if (remove) { if (!confirm('Delete this item? This cannot be undone.')) return; try { await api(`/api/admin/${remove.dataset.delete}?id=${remove.dataset.id}`, { method: 'DELETE' }); await refresh(remove.dataset.delete); message('Item deleted. It no longer appears on the live site.', true); } catch (error) { message(error.message); } } });
document.addEventListener('submit', async (event) => { const form = event.target.closest('[data-edit-form]'); if (!form) return; event.preventDefault(); setBusy(form, true); try { await save(form, form.dataset.editForm, form.dataset.id); } catch (error) { message(error.message); } finally { setBusy(form, false); } });
$('#sign-out').addEventListener('click', () => location.reload());