const dialog = document.querySelector('#booking-dialog');
const menuToggle = document.querySelector('.menu-toggle');
const mobileNav = document.querySelector('.mobile-nav');
const form = document.querySelector('#booking-form');
const message = form.querySelector('.form-message');
const escape = (value = '') => { const box = document.createElement('div'); box.textContent = String(value); return box.innerHTML; };
const naira = (value = '') => { const number = Number(String(value).replace(/[^0-9.]/g, '')); return Number.isFinite(number) && number > 0 ? `₦${number.toLocaleString('en-NG')}` : escape(value); };
const video = (url = '') => /\.(mp4|webm|mov)(\?.*)?$/i.test(url);

document.querySelectorAll('.site-header .brand, footer .brand').forEach((link) => { link.href = '/'; });

document.querySelectorAll('[data-open-booking]').forEach((button) => button.addEventListener('click', () => dialog.showModal()));
document.querySelector('.close-dialog').addEventListener('click', () => dialog.close());
dialog.addEventListener('click', (event) => { if (event.target === dialog) dialog.close(); });
menuToggle.addEventListener('click', () => { const open = mobileNav.classList.toggle('open'); menuToggle.setAttribute('aria-expanded', open); menuToggle.innerHTML = open ? '<i class="bi bi-x-lg"></i>' : '<i class="bi bi-list"></i>'; });
mobileNav.querySelectorAll('a').forEach((link) => link.addEventListener('click', () => { mobileNav.classList.remove('open'); menuToggle.setAttribute('aria-expanded', 'false'); menuToggle.innerHTML = '<i class="bi bi-list"></i>'; }));

function setOptions(select, items, label) { select.innerHTML = `<option value="">${label}</option>${items.map((item) => `<option value="${item.id}">${escape(item.title || new Date(item.starts_at).toLocaleString('en-NG', { dateStyle: 'medium', timeStyle: 'short' }))}</option>`).join('')}`; }
function renderGallery(items, socials) { const list = document.querySelector('#gallery-list'); document.querySelector('#gallery [data-social="tiktok"]')?.remove(); document.querySelector('#gallery-controls')?.remove(); document.querySelector('.gallery-heading h2').textContent = 'A closer look at Dreamy Eyes.'; list.innerHTML = items.map((item, index) => `<figure class="${index > 5 ? 'gallery-extra' : ''}" ${index > 5 ? 'style="display:none"' : ''}>${video(item.image_url) ? `<video controls preload="metadata" style="width:100%;height:435px;object-fit:cover;display:block" src="${escape(item.image_url)}" aria-label="${escape(item.alt_text || item.title)}"></video>` : `<img src="${escape(item.image_url)}" alt="${escape(item.alt_text || item.title)}">`}<figcaption><span>${escape(item.title)}</span><p>${escape(item.description || '')}</p></figcaption></figure>`).join(''); const tiktok = socials.find((item) => item.platform.toLowerCase() === 'tiktok') || { url: 'https://www.tiktok.com/@dreamy_eyes94?_r=1&_t=ZS-996kBq4hRtY' }; const controls = document.createElement('div'); controls.id = 'gallery-controls'; controls.style.cssText = 'display:flex;gap:12px;flex-wrap:wrap;margin-top:38px'; const link = document.createElement('a'); link.href = tiktok.url; link.target = '_blank'; link.rel = 'noreferrer'; link.textContent = 'View on TikTok'; link.style.cssText = 'display:inline-block;background:#400d1c;color:#f7ecdd;border:1px solid #400d1c;padding:15px 22px;font-size:11px;font-weight:700;letter-spacing:.1em;text-transform:uppercase;text-decoration:none'; controls.append(link); if (items.length > 6) { const toggle = document.createElement('button'); toggle.type = 'button'; toggle.textContent = `View more (${items.length - 6})`; toggle.style.cssText = 'background:transparent;color:#400d1c;border:1px solid #400d1c;padding:15px 22px;font-size:11px;font-weight:700;letter-spacing:.1em;text-transform:uppercase;cursor:pointer'; toggle.onclick = () => { const expanded = toggle.dataset.expanded === 'true'; list.querySelectorAll('.gallery-extra').forEach((item) => { item.style.display = expanded ? 'none' : ''; }); toggle.dataset.expanded = String(!expanded); toggle.textContent = expanded ? `View more (${items.length - 6})` : 'View less'; }; controls.append(toggle); } list.insertAdjacentElement('afterend', controls); }
function renderSocials(items) { const icons = { tiktok: 'bi-tiktok', instagram: 'bi-instagram', twitter: 'bi-twitter-x', x: 'bi-twitter-x', pinterest: 'bi-pinterest' }; const defaults = [{ platform: 'tiktok', label: '@dreamy_eyes94', url: 'https://www.tiktok.com/@dreamy_eyes94?_r=1&_t=ZS-996kBq4hRtY' }]; const byPlatform = new Map(defaults.map((item) => [item.platform, item])); items.forEach((item) => byPlatform.set(item.platform.toLowerCase(), item)); let holder = document.querySelector('#footer-socials'); if (!holder) { holder = document.createElement('div'); holder.id = 'footer-socials'; holder.className = 'footer-socials'; document.querySelector('footer>a:not(.brand)')?.replaceWith(holder); } holder.style.display = 'grid'; holder.style.gap = '10px'; holder.innerHTML = [...byPlatform.values()].map((item) => `<a style="color:#f7ecdd;font-weight:700;text-decoration:none" href="${escape(item.url)}" target="_blank" rel="noreferrer"><i class="bi ${icons[item.platform.toLowerCase()] || 'bi-link-45deg'}"></i> ${escape(item.label || item.platform)}</a>`).join(''); }
function renderContent(content) { if (content.services?.length) { document.querySelector('#menu-list').innerHTML = content.services.map((service) => `<article><span>${escape(service.title)}</span><p>${escape(service.description)}</p><strong>${naira(service.price)}</strong></article>`).join(''); setOptions(document.querySelector('#booking-service'), content.services, 'Choose a set'); } if (content.gallery?.length) renderGallery(content.gallery, content.socials || []); if (content.slots?.length) setOptions(document.querySelector('#booking-slot'), content.slots, 'Choose a date and time'); renderSocials(content.socials || []); if (content.settings?.location) { const location = document.querySelector('.contact-card .bi-geo-alt + span'); if (location) location.textContent = content.settings.location; } const refill = document.querySelectorAll('.refill-note b'); if (content.settings?.refill_two_week && refill[0]) refill[0].textContent = naira(content.settings.refill_two_week); if (content.settings?.refill_three_week && refill[1]) refill[1].textContent = naira(content.settings.refill_three_week); }
fetch('/api/content').then((response) => response.ok ? response.json() : null).then((content) => content && renderContent(content)).catch(() => {});
form.addEventListener('submit', async (event) => { event.preventDefault(); if (!form.checkValidity()) { message.textContent = 'Please complete each field so we can hold your preferred time.'; form.reportValidity(); return; } message.className = 'form-message'; message.textContent = 'Sending your request...'; try { const payload = Object.fromEntries(new FormData(form)); const response = await fetch('/api/reservations', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(payload) }); const result = await response.json(); if (!response.ok) throw new Error(result.error || 'Unable to send your request.'); message.classList.add('success'); message.textContent = 'Thank you. Your appointment request has been sent.'; form.reset(); } catch (error) { message.textContent = error.message; } });
