import { createServer } from 'node:http';
import { readFile, stat } from 'node:fs/promises';
import { extname, join, normalize } from 'node:path';

const root = process.cwd();
const config = ['SUPABASE_URL','SUPABASE_ANON_KEY','SUPABASE_SERVICE_ROLE_KEY','RESEND_API_KEY','RESEND_FROM'];
const configured = config.every((key) => process.env[key]);
const json = (res, status, body) => { res.writeHead(status, { 'Content-Type': 'application/json' }); res.end(JSON.stringify(body)); };
const readJson = async (req) => { let body=''; for await (const part of req) body+=part; return body ? JSON.parse(body) : {}; };
const sb = async (path, options = {}, service = false) => fetch(`${process.env.SUPABASE_URL}/rest/v1/${path}`, { ...options, headers: { apikey: service ? process.env.SUPABASE_SERVICE_ROLE_KEY : process.env.SUPABASE_ANON_KEY, Authorization: `Bearer ${service ? process.env.SUPABASE_SERVICE_ROLE_KEY : process.env.SUPABASE_ANON_KEY}`, 'Content-Type':'application/json', Prefer:'return=representation', ...options.headers } });
const sbJson = async (path, options = {}, service = false) => { const response = await sb(path, options, service); const data = response.status === 204 ? null : await response.json(); if (!response.ok) throw new Error(data?.message || data?.hint || data?.error || 'The database request failed.'); return data; };
async function requireAdmin(req) { const token = req.headers.authorization?.replace('Bearer ',''); if (!token) throw new Error('Sign in is required.'); const userRes = await fetch(`${process.env.SUPABASE_URL}/auth/v1/user`, { headers: { apikey:process.env.SUPABASE_ANON_KEY, Authorization:`Bearer ${token}` } }); if (!userRes.ok) throw new Error('Your session has expired.'); const user = await userRes.json(); const profile = await sb(`profiles?select=is_admin&id=eq.${user.id}`, {}, true).then((r) => r.json()); if (!profile[0]?.is_admin) throw new Error('Admin access is required.'); }
async function content() { const [services,gallery,socials,slots,settings] = await Promise.all([sbJson('services?select=*&is_published=eq.true&order=sort_order.asc'),sbJson('gallery_items?select=*&is_published=eq.true&order=sort_order.asc'),sbJson('social_links?select=*&is_published=eq.true&order=sort_order.asc'),sbJson(`appointment_slots?select=*&is_available=eq.true&starts_at=gte.${encodeURIComponent(new Date().toISOString())}&order=starts_at.asc`),sbJson('site_settings?select=location,refill_two_week,refill_three_week&id=eq.1')]); return { services,gallery,socials,slots,settings:settings[0] || {} }; }
const tables = new Set(['services','gallery_items','social_links','appointment_slots','reservations','site_settings']);
createServer(async (req,res) => { try { const url = new URL(req.url, `http://${req.headers.host}`); if (url.pathname === '/api/content' && req.method === 'GET') return json(res,200,await content()); if (url.pathname === '/api/config' && req.method === 'GET') return json(res,200,{supabaseUrl:process.env.SUPABASE_URL,anonKey:process.env.SUPABASE_ANON_KEY,ready:configured});
  if (url.pathname === '/api/reservations' && req.method === 'POST') { if (!configured) return json(res,503,{error:'Booking is not connected yet.'}); const data=await readJson(req); if (!data.name || !data.phone || !data.service || !data.slot) return json(res,400,{error:'Please complete every booking field.'}); const slots=await sbJson(`appointment_slots?select=*&id=eq.${data.slot}&is_available=eq.true`,{},true); if (!slots[0]) return json(res,409,{error:'That appointment is no longer available.'}); const services=await sbJson(`services?select=*&id=eq.${data.service}`,{},true); const settings=await sbJson('site_settings?select=reservation_email&id=eq.1',{},true); const reservation={client_name:data.name,phone:data.phone,service_id:data.service,slot_id:data.slot,status:'pending'}; await sbJson('reservations',{method:'POST',body:JSON.stringify(reservation)},true); const recipient=settings[0]?.reservation_email; const email=await fetch('https://api.resend.com/emails',{method:'POST',headers:{Authorization:`Bearer ${process.env.RESEND_API_KEY}`,'Content-Type':'application/json'},body:JSON.stringify({from:process.env.RESEND_FROM,to:[recipient],subject:`New Dreamy Eyes appointment: ${data.name}`,html:`<h2>New appointment request</h2><p><b>Client:</b> ${data.name}</p><p><b>Phone:</b> ${data.phone}</p><p><b>Service:</b> ${services[0]?.title || 'Selected service'}</p><p><b>Time:</b> ${new Date(slots[0].starts_at).toLocaleString('en-NG')}</p>`})}); if(!email.ok) throw new Error('Reservation saved, but the notification email could not be delivered.'); return json(res,201,{ok:true}); }
  if (url.pathname.startsWith('/api/admin/')) { if (!configured) return json(res,503,{error:'Add environment variables first.'}); await requireAdmin(req); const table=url.pathname.split('/').pop(); if(!tables.has(table)) return json(res,404,{error:'Unknown content type.'}); const id=url.searchParams.get('id'); const order = table === 'appointment_slots' ? '&order=starts_at.asc' : table === 'reservations' ? '&order=created_at.desc' : table === 'site_settings' ? '' : '&order=sort_order.asc,created_at.desc'; if(req.method==='GET') return json(res,200,await sbJson(`${table}?select=*${order}`,{},true)); const data=await readJson(req); if(req.method==='POST' && table !== 'reservations' && table !== 'site_settings') return json(res,201,await sbJson(table,{method:'POST',body:JSON.stringify(data)},true)); if(req.method==='PATCH'&&id) return json(res,200,await sbJson(`${table}?id=eq.${id}`,{method:'PATCH',body:JSON.stringify(data)},true)); if(req.method==='DELETE'&&id) { if(table==='services') await sbJson(`reservations?service_id=eq.${id}`,{method:'PATCH',body:JSON.stringify({service_id:null})},true); if(table==='appointment_slots') await sbJson(`reservations?slot_id=eq.${id}`,{method:'PATCH',body:JSON.stringify({slot_id:null})},true); await sbJson(`${table}?id=eq.${id}`,{method:'DELETE'},true); return json(res,204,{}); } }
  const relative = url.pathname === '/' ? 'index.html' : url.pathname === '/admin' ? 'admin.html' : url.pathname.slice(1); const file = join(root,normalize(relative)); if(!file.startsWith(root)) throw new Error('Not found'); const body=await readFile(file); const types={'.html':'text/html','.js':'text/javascript','.css':'text/css','.jpeg':'image/jpeg','.jpg':'image/jpeg'}; res.writeHead(200,{'Content-Type':types[extname(file)]||'application/octet-stream'}); res.end(body);
} catch(error) { json(res,error.message==='Not found'?404:500,{error:error.message||'Server error'}); } }).listen(process.env.PORT||3000,()=>console.log(`Dreamy Eyes CMS: http://localhost:${process.env.PORT||3000}`));
