const config = ['SUPABASE_URL', 'SUPABASE_ANON_KEY', 'SUPABASE_SERVICE_ROLE_KEY', 'RESEND_API_KEY', 'RESEND_FROM'];
const configured = () => config.every((key) => process.env[key]);
const send = (res, status, body) => res.status(status).json(body);
const sb = async (path, options = {}, service = false) => fetch(`${process.env.SUPABASE_URL}/rest/v1/${path}`, { ...options, headers: { apikey: service ? process.env.SUPABASE_SERVICE_ROLE_KEY : process.env.SUPABASE_ANON_KEY, Authorization: `Bearer ${service ? process.env.SUPABASE_SERVICE_ROLE_KEY : process.env.SUPABASE_ANON_KEY}`, 'Content-Type': 'application/json', Prefer: 'return=representation', ...options.headers } });
const sbJson = async (path, options = {}, service = false) => { const response = await sb(path, options, service); const data = response.status === 204 ? null : await response.json(); if (!response.ok) throw new Error(data?.message || data?.hint || data?.error || 'The database request failed.'); return data; };
async function requireAdmin(req) { const token = req.headers.authorization?.replace('Bearer ', ''); if (!token) throw new Error('Sign in is required.'); const userRes = await fetch(`${process.env.SUPABASE_URL}/auth/v1/user`, { headers: { apikey: process.env.SUPABASE_ANON_KEY, Authorization: `Bearer ${token}` } }); if (!userRes.ok) throw new Error('Your session has expired.'); const user = await userRes.json(); const profile = await sbJson(`profiles?select=is_admin&id=eq.${user.id}`, {}, true); if (!profile[0]?.is_admin) throw new Error('Admin access is required.'); }
async function content() { const [services, gallery, socials, slots, settings] = await Promise.all([sbJson('services?select=*&is_published=eq.true&order=sort_order.asc'), sbJson('gallery_items?select=*&is_published=eq.true&order=sort_order.asc'), sbJson('social_links?select=*&is_published=eq.true&order=sort_order.asc'), sbJson(`appointment_slots?select=*&is_available=eq.true&starts_at=gte.${encodeURIComponent(new Date().toISOString())}&order=starts_at.asc`), sbJson('site_settings?select=location,refill_two_week,refill_three_week&id=eq.1')]); return { services, gallery, socials, slots, settings: settings[0] || {} }; }
const tables = new Set(['services', 'gallery_items', 'social_links', 'appointment_slots', 'reservations', 'site_settings']);

export default async function handler(req, res) {
  try {
    const path = Array.isArray(req.query.path) ? req.query.path.join('/') : req.query.path || '';
    if (path === 'content' && req.method === 'GET') return send(res, 200, await content());
    if (path === 'config' && req.method === 'GET') return send(res, 200, { supabaseUrl: process.env.SUPABASE_URL, anonKey: process.env.SUPABASE_ANON_KEY, ready: configured() });
    if (path === 'reservations' && req.method === 'POST') { if (!configured()) return send(res, 503, { error: 'Booking is not connected yet.' }); const data = req.body || {}; if (!data.name || !data.phone || !data.service || !data.slot) return send(res, 400, { error: 'Please complete every booking field.' }); const slots = await sbJson(`appointment_slots?select=*&id=eq.${data.slot}&is_available=eq.true`, {}, true); if (!slots[0]) return send(res, 409, { error: 'That appointment is no longer available.' }); const services = await sbJson(`services?select=*&id=eq.${data.service}`, {}, true); const settings = await sbJson('site_settings?select=reservation_email&id=eq.1', {}, true); await sbJson('reservations', { method: 'POST', body: JSON.stringify({ client_name: data.name, phone: data.phone, service_id: data.service, slot_id: data.slot, status: 'pending' }) }, true); const email = await fetch('https://api.resend.com/emails', { method: 'POST', headers: { Authorization: `Bearer ${process.env.RESEND_API_KEY}`, 'Content-Type': 'application/json' }, body: JSON.stringify({ from: process.env.RESEND_FROM, to: [settings[0]?.reservation_email], subject: `New Dreamy Eyes appointment: ${data.name}`, html: `<h2>New appointment request</h2><p><b>Client:</b> ${data.name}</p><p><b>Phone:</b> ${data.phone}</p><p><b>Service:</b> ${services[0]?.title || 'Selected service'}</p><p><b>Time:</b> ${new Date(slots[0].starts_at).toLocaleString('en-NG')}</p>` }) }); if (!email.ok) throw new Error('Reservation saved, but the notification email could not be delivered.'); return send(res, 201, { ok: true }); }
    if (path.startsWith('admin/')) { if (!configured()) return send(res, 503, { error: 'Add environment variables first.' }); await requireAdmin(req); const table = path.split('/')[1]; if (!tables.has(table)) return send(res, 404, { error: 'Unknown content type.' }); const id = req.query.id; const order = table === 'appointment_slots' ? '&order=starts_at.asc' : table === 'reservations' ? '&order=created_at.desc' : table === 'site_settings' ? '' : '&order=sort_order.asc,created_at.desc'; if (req.method === 'GET') return send(res, 200, await sbJson(`${table}?select=*${order}`, {}, true)); if (req.method === 'POST' && !['reservations', 'site_settings'].includes(table)) return send(res, 201, await sbJson(table, { method: 'POST', body: JSON.stringify(req.body || {}) }, true)); if (req.method === 'PATCH' && id) return send(res, 200, await sbJson(`${table}?id=eq.${id}`, { method: 'PATCH', body: JSON.stringify(req.body || {}) }, true)); if (req.method === 'DELETE' && id) { if (table === 'services') await sbJson(`reservations?service_id=eq.${id}`, { method: 'PATCH', body: JSON.stringify({ service_id: null }) }, true); if (table === 'appointment_slots') await sbJson(`reservations?slot_id=eq.${id}`, { method: 'PATCH', body: JSON.stringify({ slot_id: null }) }, true); await sbJson(`${table}?id=eq.${id}`, { method: 'DELETE' }, true); return res.status(204).end(); } }
    return send(res, 404, { error: 'Not found.' });
  } catch (error) { return send(res, 500, { error: error.message || 'Server error' }); }
}
